CREATE SCHEMA Airbnb;
use Airbnb;

#DROP TABLE User;
CREATE TABLE User (
UID INT,
Name VARCHAR(30) NOT NULL,
Email VARCHAR(30) NOT NULL,
Password VARCHAR(30) NOT NULL,
DOB DATE NOT NULL,
PictureURL VARCHAR(200),
Address VARCHAR(100),
Phone VARCHAR(15) NOT NULL,
EmName VARCHAR(30),
EmRel VARCHAR(20),
EmEmail VARCHAR(20) NOT NULL,
PRIMARY KEY (UID));

#DROP TABLE Guest;
CREATE TABLE Guest (
UID INT,
NumGuestRatings INT,
AvgGuestRatings FLOAT,
CreditCardNo INT,
PRIMARY KEY (UID));

#DROP TABLE GuestPastBookings;
CREATE TABLE GuestPastBookings (
GuestUID INT,
BID INT,
PRIMARY KEY (GuestUID, BID));

#DROP TABLE CreditCard;
CREATE TABLE CreditCard (
CardNo INT,
CSV INT NOT NULL,
Expiration DATE NOT NULL,
Name VARCHAR (30) NOT NULL,
Address VARCHAR(100),
PRIMARY KEY (CardNo));

#DROP TABLE Host;
CREATE TABLE Host ( 
UID INT,
NumHostRatings INT,
AvgHostRatings FLOAT,
AVGPropertyRating FLOAT,
BankAccountNo INT NOT NULL,
PRIMARY KEY (UID));

#DROP TABLE BankAccount;
CREATE TABLE BankAccount (
AccountNo INT,
Type VARCHAR(15),
PRIMARY KEY (AccountNo));

#DROP TABLE Message;
CREATE TABLE Message (
MID INT,
GestUID INT NOT NULL,
HostUID INT NOT NULL,
DateTime DATE,
Receiver VARCHAR(30),
Sender VARCHAR(30),
Body VARCHAR(400),
PRIMARY KEY (MID));

#DROP TABLE GuestOrHostReview;
CREATE TABLE GuestOrHostReview (
GHRID INT,
GuestUID INT NOT NULL,
HostUID INT NOT NULL,
Comment VARCHAR(200) NOT NULL,
Rating INT NOT NULL,
ReviewDate DATE,
PRIMARY KEY (GHRID));

#DROP TABLE Property;
CREATE TABLE Property (
PID INT,
Name VARCHAR(30) NOT NULL,
Address VARCHAR(100) NOT NULL,
HostUID INT NOT NULL,
MaxGuests INT,
NumBedrooms INT,
Description VARCHAR(100) NOT NULL,
NumBathrooms INT,
CancelPeriod VARCHAR(20),
RefundRate FLOAT,
NumRatings INT,
AvgRatings FLOAT,
NightlyFee FLOAT,
CleaningFee FLOAT,
AirbnbServiceFee FLOAT,
PRIMARY KEY (PID));

#DROP TABLE PropertyCategories;
CREATE TABLE PropertyCategories (
PropertyID INT,
Category VARCHAR(20) NOT NULL,
PRIMARY KEY (PropertyID));

#DROP TABLE PropertyPhotos;
CREATE TABLE PropertyPhotos (
PropertyID INT,
PhotoURL VARCHAR(200) NOT NULL,
PRIMARY KEY (PropertyID));

#DROP TABLE PropertyTimeSlots;
CREATE TABLE PropertyTimeSlots (
PropertyID INT,
StartDate DATE,
EndDate DATE,
Availability TINYINT DEFAULT 1,
PRIMARY KEY (PropertyID));

#DROP TABLE PropertyReview;
CREATE TABLE PropertyReview (
PRID INT,
GuestUID INT NOT NULL,
PropertyID INT NOT NULL,
Comment VARCHAR(200),
PropReviewDate DATE,
CleanlinessRating INT,
AccuracyRating INT,
CommunicationRating INT,
CheckInRating INT,
ValueRating INT,
OverallRating INT,
PRIMARY KEY (PRID));

#DROP TABLE PropertyReviewPhotos;
CREATE TABLE PropertyReviewPhotos (
ReviewID INT,
PhotoURL VARCHAR(200) NOT NULL,
PRIMARY KEY (ReviewID));

#DROP TABLE Booking;
CREATE TABLE Booking(
BID INT,
GuestUID INT NOT NULL,
PropertyID INT NOT NULL,
Checkin DATE,
Checkout DATE,
NumGuest INT,
TotalPrice FLOAT,
NightsStayed INT,
PromotionCode VARCHAR(20),
Tax Float,
CancellationDate DATE DEFAULT NULL,
PropRefundRate FLOAT,
RefundedAmount FLOAT,
PRIMARY KEY (BID));

ALTER TABLE Guest ADD CONSTRAINT GuestFK1 FOREIGN KEY(UID) REFERENCES User(UID) ON DELETE CASCADE;
ALTER TABLE GuestPastBookings ADD CONSTRAINT GuestPastBookingsFK1 FOREIGN KEY(GuestUID) REFERENCES Guest(UID) ON DELETE CASCADE;
ALTER TABLE GuestPastBookings ADD CONSTRAINT GuestPastBookingsFK2 FOREIGN KEY(BID) REFERENCES Booking(BID) ON DELETE CASCADE;
ALTER TABLE CreditCard ADD CONSTRAINT CreditCardFK1 FOREIGN KEY(CardNo) REFERENCES Guest(CreditCardNo) ON DELETE CASCADE;
ALTER TABLE Host ADD CONSTRAINT HostFK1 FOREIGN KEY(UID) REFERENCES User(UID) ON DELETE CASCADE;
ALTER TABLE BankAccount ADD CONSTRAINT BankAccountFK1 FOREIGN KEY(AccountNo) REFERENCES Host(BankAccountNo) ON DELETE CASCADE;
ALTER TABLE Message ADD CONSTRAINT MessageFK1 FOREIGN KEY(GuestUID) REFERENCES Guest(UID) ON DELETE CASCADE;
ALTER TABLE Message ADD CONSTRAINT MessageFK2 FOREIGN KEY(HostUID) REFERENCES Host(UID) ON DELETE CASCADE;
ALTER TABLE Property ADD CONSTRAINT PropertyFK1 FOREIGN KEY(HostUID) REFERENCES Host(UID) ON DELETE CASCADE;
ALTER TABLE PropertyCategories ADD CONSTRAINT PropertyCategoriesFK1 FOREIGN KEY(PropertyID) REFERENCES Property(PID) ON DELETE CASCADE;
ALTER TABLE PropertyPhotos ADD CONSTRAINT PropertyPhotosFK1 FOREIGN KEY(PropertyID) REFERENCES Property(PID) ON DELETE CASCADE;
ALTER TABLE PropertyTimeSlots ADD CONSTRAINT PropertyTimeSlotsFK1 FOREIGN KEY(PropertyID) REFERENCES Property(PID) ON DELETE CASCADE;
ALTER TABLE PropertyReview ADD CONSTRAINT PropertyReviewFK1 FOREIGN KEY(GuestUID) REFERENCES Guest(UID) ON DELETE CASCADE;
ALTER TABLE PropertyReview ADD CONSTRAINT PropertyReviewFK2 FOREIGN KEY(PropertyID) REFERENCES Property(PID) ON DELETE CASCADE;
ALTER TABLE PropertyReviewPhotos ADD CONSTRAINT PropertyReviewPhotosFK1 FOREIGN KEY(ReviewID) REFERENCES PropertyReview(PRID) ON DELETE CASCADE;
ALTER TABLE Booking ADD CONSTRAINT BookingFK1 FOREIGN KEY(GuestUID) REFERENCES Guest(UID) ON DELETE CASCADE;
ALTER TABLE Booking ADD CONSTRAINT BookingFK2 FOREIGN KEY(PropertyID) REFERENCES Property(PID) ON DELETE CASCADE;
